apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudkit-aap-config-as-code-manifest-ig
  namespace: fulfillment-aap
spec:
  dataFrom:
  - extract:
      key: innabox/hypershift1/fulfillment-aap/cloudkit-aap-config-as-code-manifest-ig
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: cloudkit-aap-config-as-code-manifest-ig
    template:
      engineVersion: v2
      data:
        license.zip: '{{ index . "license.zip" | b64dec }}'  # license.zip is already b64, we don't want external secrets to encode it one more time
