apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vault-operator
    namespace: vault-operator
    repo: oci://ghcr.io/bank-vaults/helm-charts
    version: 1.22.6
    includeCRDs: true
    skipTests: true
    releaseName: vault-operator
